sanitize-branch-name/README.md
sanitize-branch-name/action.yml
sanitize-branch-name/sanitize.sh

based on the [global shared equivalent](https://github.com/camunda/jenkins-global-shared-library/blob/master/src/org/camunda/helper/GitUtilities.groovy#L4-L10).
removes `dependabot/`, `renovate/`,puts to lowercase, transforms anything not `a-z0-9` to `-` and cuts at a specified length or returns the whole string.
Decided for this approach as I will have to use it a couple of times in different repositories and don't intend to copy & paste it every time.
Test see here --> https://github.com/camunda/infra-test-3375/actions/runs/3043925402/jobs/4903735199
related to camunda/team-infrastructure#28

chore(action): add branch sanitze action

---

sanitize-branch-name/sanitize.sh

related to cawemo / web-modeler change.
Required as otherwise their branch names are too long, due to sticking to previous `-deploy` name.
related to camunda/team-infrastructure#28

chore(sanitize): remove -deploy from branch names

---

build-docker-image/action.yml

This PR will add docker _build-args_ as an optional input for the docker _build_ action.
Related: camunda/team-infrastructure#144

chore(gha) Adding optional 'build-args' input to docker build step.

---

download-center-upload/README.md
download-center-upload/action.yml

Moves the action from [previous repository](https://github.com/camunda/download-center-upload-action) to align with the global actions repository.
Items I changed on top:
- removed `${{ inputs.artifact_file }}` from the target copy, allowing to e.g. use wildcards or whitespace separated string to push multiple artifacts in addition to defining a single file.
- added `-m` to use parallel multi-threaded/multi-processing copy
- adjusted the documentation
after merge:
- archive https://github.com/camunda/download-center-upload-action
- adjust eventual extra docs of e.g. awesome action list / confluence? / others

chore(download-center-upload): move action from previous internal repo

---

build-docker-image/README.md
build-docker-image/action.yml
kubernetes-image-replace/README.md
kubernetes-image-replace/action.yml

related to https://github.com/camunda/team-infrastructure/issues/150
Adds several backward-compatible adjustments to the `build-docker-image` action.
E.g. allows setting `extra-tags` or exposure of outputs, so you can further use them for other actions.
Added also a `force_push` option, see example run: https://github.com/camunda/int-airtable-loader/actions/runs/4125315864/jobs/7125706871 . Reasoning is that not everyone follows the tagging schema and it can be useful to "force" an image push.
Additionally creates an action that allows settings the image of a container within a deployment or statefulset.
Example usage for both changes:
https://github.com/camunda/int-airtable-loader/actions/runs/4124077850/jobs/7122889524
Metadata is sadly often excluded in GitHub Actions if set as output …

chore(actions): introduce new kubernetes image replace action + adjust docker build

---

configure-pull-request/README.md
configure-pull-request/action.yml

Related to https://github.com/camunda/team-infrastructure/issues/204
Add a new composite GitHub action to configure a Pull Request. It is part of the refactoring of the `maintenance_project.yml` workflow but the logic can be reused for other needs.

Add a new 'configure-pull-request' composite GitHub action

---

teams/infra/configure-maintenance-pull-request/README.md
teams/infra/configure-maintenance-pull-request/action.yml

Related to https://github.com/camunda/team-infrastructure/issues/204
Add a new composite GitHub action to configure a maintenance Pull Request according to the Infra team [guidelines](https://github.com/camunda/infra-global-github-actions/pull/32/files#diff-f6a634806877868e521ee7057c9d223f2d0ce012e7d42cef6a128ddc45c4cf5bR5-R11). It is part of the refactoring of the `maintenance_project.yml` workflow.
**This PR is still in draft mode**. Here are the remaining tasks before merging:

Add a new 'configure-maintenance-pull-request' composite GitHub action

---

generate-github-app-token-from-vault-secrets/README.md
generate-github-app-token-from-vault-secrets/action.yml

Related to https://github.com/camunda/team-infrastructure/issues/204
Add a new composite GitHub action to generate a GitHub token from Github App secrets (ID & Private Key) stored in Vault. It is part of the refactoring of the `maintenance_project.yml` workflow.

Add a new `generate-github-app-token-from-vault-secrets` composite GHA

---

build-docker-image/README.md
build-docker-image/action.yml

This PR will add some additional inputs for the `docker build and push` action and make some configurable with sensible defaults:
- build_context: Many images place dockerfiles and install scripts in subdirectories. This will default to root.
- build_allow: This allows configuring additional entitlements when building images that require this.
- buildx_driver: Allows you to specify which driver to use for the buildx builder.
- Builx_version: Allows you to specify a certain revision of the buildx action to use when building.

chore(gha) Adding additional inputs for docker build.

---

.github/renovate.json5

Related to camunda/team-infrastructure#204
Since the new maintenance workflow handles labeling (dependency-upgrade) and review request for all maintenance PRs, the Renovate configuration can be adjusted to no longer perform these same actions.

chore(renovate): Remove the Renovate configuration for labeling (dependency-upgrade) and requesting review for new maintenance PRs

---

build-docker-image/action.yml

set default for load input as otherwise it fails with nothing defined.
```
Error: Input does not meet YAML 1.2 "Core Schema" specification: load
```

chore(build-docker-image): set default for load input

---

preview-env/create/action.yml
preview-env/destroy/action.yml

Followed guide in https://confluence.camunda.com/display/SRE/ArgoCD
Related: https://camunda.slack.com/archives/CHY2S7KDJ/p1677159633536829

chore(preview-env): Use ArgoCD 2.5.11 by default

---

argocd-sync-applications/README.md
argocd-sync-applications/action.yml
yq-yaml-processor/README.md
yq-yaml-processor/action.yml

Related to https://github.com/camunda/team-infrastructure/issues/268
Add three new GitHub actions:
- [edit-and-sync-configurations-managed-by-argocd](https://github.com/camunda/infra-global-github-actions/pull/44/files#diff-7082b988058bc6a5612281406d4beb7e2e911306468d290356e6456d779646ca) to automate the update of the configurations of Kubernetes resources (source of truth) managed by ArgoCD.
- [sync-argocd-applications](https://github.com/camunda/infra-global-github-actions/pull/44/files#diff-137c4a613cb300c4adc97ea8c894a29bab7b54daf07506e4d0ac6540d4decd94) to  sync ArgoCD applications.
- [yq-yaml-processor](https://github.com/camunda/infra-global-github-actions/pull/44/files#diff-92c14ad80dadf917b56ea47d2c3b30902bb4a76d71a8416811ecf7cd23fe1673) to process YAML content by leveraging the …

Add three new GitHub actions to edit and sync the configurations of Kubernetes resources managed by ArgoCD

---

assert-camunda-git-emails/README.md
assert-camunda-git-emails/check.sh

Allows commits from Snyk as more and more engineering teams are adopting the solution. See https://github.com/camunda/web-modeler/actions/runs/5038877138/jobs/9036654407?pr=4738 for an example of a failed run without this addition.

feat(action): allow snyk bot

---

.tool-versions
submit-build-status/action.yml

We discovered that GHA self-hosted runner images based on Ubuntu 22.04 do not contain `python` by default anymore - find the background here: https://github.com/actions/actions-runner-controller/pull/2050
We only need Python here for input validation (nicer to code than in Bash) but it can be done in Bash as well which avoids having to install Python just for this.
Example runs:
- failed run when one input is too long (I reduced the limit to 2 chars): https://github.com/camunda/infra-core/actions/runs/5058585353/jobs/9078888781?pr=5855
- successful run with proper inputs: https://github.com/camunda/infra-core/actions/runs/5058585353/jobs/9078992674?pr=5855

Don't use Python in submit-build-action

---

.github/renovate.json5
argocd-sync-applications/action.yml
preview-env/create/action.yml
preview-env/destroy/action.yml

This fixes the following renovate configurations:
- `rhysd/actionlint` -> github tag versions were not correctly extracted
- `argocd` -> use the docker registry `quay.io/argoproj/argocd` to get new versions + group argocd-related deps

chore(renovate): fix configurations for ArgoCD clients and actionlint

---

.github/actionlint.yaml
.github/workflows/test-common-tooling.yml
common-tooling/README.md
common-tooling/action.yml

related to https://github.com/camunda/team-infrastructure/issues/389
The action pretty much just copies the inputs from the existing actions and prefixes them with whatever the source is. Meaning you're in full control to overwrite anything.
Before running a check is done to see what's available to potentially skip installing a software. Requires `overwrite = false`. Default is to overwrite to have the same versions on `hosted` and `self-hosted` since on `hosted` everything is available.
Creates `common-tooling` action with some defaults on.
Node - 16 lts --> most used by GitHub Actions
Python - 3.11
Java - 17 LTS
Rest is latest where possible.
Added a workflow to test the action with different parameters.
In the case software is already available, the run is a lot quicker, see GHA vs …

chore(gha): add common-tooling action for easier use with self-hosted runners

---

sanitize-branch-name/action.yml

To avoid escaping issues when special chars like `(` or `)` are present in the source branch name.
Related: https://camunda.slack.com/archives/C5AHF1D8T/p1694065338633579
Tested locally:
```bash
$ echo "branch_name=$(./sanitize.sh '5978-Postpend-(copy)-for$$-templates-saved-as-copies' 31)"
branch_name=5978-postpend--copy--for---temp
```

chore(sanitize-branch-name): Quote the branch name before passing it to sanitize.sh

---

preview-env/create/action.yml

Related to ask-infra request https://camunda.slack.com/archives/C5AHF1D8T/p1694771504886029.
Permission denied issues are encountered by Operate when deploying a preview environment even though the token used has the right permissions.
It's not related to the Dex crash loop as mentioned in this [comment](https://camunda.slack.com/archives/CHY2S7KDJ/p1694430900442579?thread_ts=1694428700.790319&cid=CHY2S7KDJ). Dex is not part of the authorization validation process.
The most likely hypothesis is a consistency problem between the creation of the app and the execution of the wait command immediately afterwards, as suggested [here](https://camunda.slack.com/archives/CTYKBESCE/p1695026795048189?thread_ts=1695026504.084219&cid=CTYKBESCE), but I couldn't reproduce this scenario in dev.
As a …

chore(preview-env/create): Add a retry logic to the `argocd` `wait` command

---

preview-env/clean/github.sh

If pull requests have comments that consist out of several thousand characters, our [script fails](https://github.com/camunda/camunda-optimize/actions/runs/6783837906/job/18438912286?pr=9321) with the following error:
`/home/runner/work/_actions/camunda/infra-global-github-actions/fix-preview-cleanup/preview-env/clean/cleanup.sh: line 296: /usr/bin/jq: Argument list too long`
This is due to passing the JSON with all the PR data via command line to `jq` and exceeding the maximum allowed length. This didn't happen so far in any project of Camunda since comments are usually short (enough). But Optimize employs SonarCloud which posts a comment with >3500 characters under each PR. We do not care about those comments in the cleanup logic (only our own) so I propose to filter for too long …

chore(preview-env/clean): don't crash on long comments in PRs

---

build-docker-image/action.yml

Disable provenance for the Docker images
Context: https://github.com/camunda/tasklist/pull/4033

chore(build-docker-image): disable provenance feature

---

.github/renovate.json5

Limit Renovate one to only happen on Saturdays and skip patches (it's updated very frequently)

chore(renovate): Automerge pre-commit hooks

---

submit-build-status/action.yml

It turns out `$GITHUB_RUN_ID` does not change if a workflow run is re-run leading potentially to duplicate rows. We also have to consider the separate `$GITHUB_RUN_ATTEMPT` variable according to https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
The options I considered were:
* adding a new optional column called e.g. `build_attempt` to `build_status_v2` table (cannot add mandatory fields to existing tables) - more effort and wouldn't be mandatory
* creating a new `build_status_v3` table with mandatory column `build_attempt` - more effort and makes the `build_status_v2` table specific to only GHA wihle it is intended to be abstract from a specific CI (should also be able to hold Jenkins info)
* extending the value of the existing `build_id` …

chore(submit-build-status): ensure unique build_id

---

submit-build-status/action.yml

This feature together with a Vault secret for the dev environment ingest allows test new CI Analytics features (new table schemas etc) on a branch and ingest them to BigQuery tables in `dev` environment of Infra.
Tested in https://github.com/camunda/zeebe/pull/17517 and working.

chore(submit-build-status): optional BQ table name input for testing in dev, defaults to prod

---

submit-build-status/action.yml

This PR needs https://github.com/camunda/infra-core/pull/7580 to collect and ingest additional metadata about GHA runs into CI Analytics.
The new info is helpful for users and Infra operators and easy to collect:
* `build_base_ref` is the target branch of a PR or merge queue run. This is important if you have multiple persistent branches like `main` and `stable/*` to identify for which branch a GHA workflow run was done and filter statistics e.g. only for `main`
* `runner_name` in lowercase like "github actions 123" for Github-hosted runners or the agent name of our self-hosted runners, allows Infra to distinguish and isolate problems with self-hosted runners
* `runner_arch` in lowercase is nice to know in case arm64 or amd64
* `runner_os` in lowercase in case we ever do esoteric stuff on …

chore(submit-build-status): add extra info about base ref and runner

---

submit-build-status/action.yml

If we are on Windows we have to use a different executable name apparently for the BigQuery client executable.
Solution via https://stackoverflow.com/questions/72924110/how-can-one-detect-if-a-github-actions-runner-is-running-in-ubuntu-or-windows to detect if we are on Windows and https://stackoverflow.com/questions/28464658/bigquery-command-line-tool-on-windows to know the correct executable name: works -> https://github.com/camunda/zeebe/actions/runs/8967179607/job/24627763741?pr=18224
Found in https://github.com/camunda/zeebe/pull/18224

chore(submit-build-status): support windows

---

submit-build-status/action.yml

In matrix builds there are multiple instances of the same job (with same name) launched and if all of them submit build status there will be duplicate rows. Allowing the user to override this with their custom matrix job names helps to avoid this.
It also helps in situations when a build status on behalf of another (cancelled) job should be submitted e.g. when a runner dies.

chore(submit-build-status): support overriding default job_name e.g. for matrix builds

---

submit-build-status/action.yml

Adds a new (optional) input where users of this action can submit how long the build of the GHA job took. This is preferably determined by stopping the time from start to finish of the job.

chore(submit-build-status): add optional build duration parameter

---

submit-aborted-gha-status/action.yml

When the runner loses connection to GH the `runner_name` field for a job from the API is empty.
I went for the alternative to parse the human-readable annotations that GH API returns which is only the 2nd best approach (fragile to future changes obviously).
Example API call for a GHA workflow job that has an empty `runner_name`: `gh api "repos/camunda/camunda/actions/jobs/28355737949"`
This helps the initiative https://github.com/camunda/camunda/issues/18210

chore(submit-aborted-gha-status): fix edge case where `runner_name` is empty

---

setup-yarn-cache/README.md
setup-yarn-cache/action.yml

This action was originally created in https://github.com/camunda/camunda/issues/21427 but is now relocated for wider use also in other repositories (disccused in [Slack](https://camunda.slack.com/archives/CHY2S7KDJ/p1725364793383679?thread_ts=1725281533.019179&cid=CHY2S7KDJ)).
Noteworthy is the new input for this action `cache_create_branch_regex` which allows configuring on which branches to save the cache on (done via Bash now instead of GHA expression to allow parameterization), the defaults suit the C8 monorepo to avoid repeating configuration.
The new action is successfully used in https://github.com/camunda/camunda/actions/runs/10699692498/job/29661839825?pr=21915 as an example

feat(setup-yarn-cache): add new action, from the C8 monorepo

---

download-center-upload/action.yml

After https://github.com/camunda/infra-global-github-actions/pull/281, we're using `gcloud storage` instead of `gsutil` to upload files to the Download Center buckets.
`gcloud storage cp` has a different behaviour for small and larger (>150MB) files: for larger ones it tries to use parallel composite upload [approach](https://cloud.google.com/storage/docs/parallel-composite-uploads). However, this approach has a lot of demands on the bucket's configutation to work, and our download center buckets don't have them:
```
WARNING: Destination has a default storage class other than "STANDARD", hence parallel composite upload will not be performed. If you would like to disable this check, run: gcloud config set storage/parallel_composite_upload_compatibility_check=False
```
However, `gcloud …

chore(download-center-upload): Disable parallel composite uploads

---

submit-aborted-gha-status/README.md
submit-aborted-gha-status/action.yml
submit-build-status/README.md
submit-build-status/action.yml

This PR adds `build_head_ref` parameter to build status actions and requires https://github.com/camunda/infra-core/pull/8624 in production to work.
related to https://github.com/camunda/camunda/issues/24549

chore(build status actions): add head ref parameter

---

actionlint/action.yml

Related to: camunda/team-infrastructure#620

ci: fix infinite loop in actionlint

---

build-docker-image/README.md
build-docker-image/action.yml

Skip authenticating with a Docker registry using username/password in case of the caller workflow uses Google Workload Identity.
Related:
camunda/team-infrastructure/issues/629

chore(feat): enable using google workload identity

---

is-cache-enabled/action.yml

I've created a dedicated PR for the `is-cache-enabled` composite action so that I will be able to reference it directly in the other composite actions as `camunda/infra-global-github-actions/is-cache-enabled@main`

chore: creates the is-cache-enabled action alone

---

setup-yarn-cache/action.yml

I've moved the setup-yarn-cache code (and its dependency on is-cache-enabled) to a dedicated PR.
This commit has been used also for testing on the monorepo
- https://github.com/camunda/camunda/pull/26294
This will replace:
- https://github.com/camunda/infra-global-github-actions/pull/318

Camunda 24303 use composite action to check caching

---

build-docker-image/action.yml

Add a new `add_hosts` input to enable user to set a list of custom host-to-IP mapping.

chore(build-docker-image): add add_hosts input

---

submit-test-status/action.yml

Small change I noticed while working on https://github.com/camunda/camunda/pull/26715 that showing the test record input can potentially result in many 100 lines of output. I'd propose to not echo this.

chore(submit-test-status): disable echoing potentially long test record input

---

submit-test-status/README.md
submit-test-status/action.yml

Populate the new `job_name` column as done by the sister action `submit-build-status`: https://github.com/camunda/infra-core/pull/8973
Related to https://github.com/camunda/camunda/issues/26930

chore(submit-test-status): add GH job name for unique relation to build status

---

is-cache-enabled/action.yml

fix: declare the expected output for is-cache-enabled

---

.github/renovate.json5
README.md

In camunda's renovate shared configuration, actionlint patch updates are automerged by default. 
Adding the same rule here to simplify maintenance

chore: setup automerge for actionlint patch updates

---

preview-env/destroy/README.md
preview-env/destroy/action.yml

This PR is to include a new step to delete the deployments and the environments as part of the `preview-env/destroy` composite action
Related to: camunda/team-infrastructure#456

Delete GitHub deployments/environments when destroying preview-env

---

.github/renovate.json5

ArgoCD patch releases should be automerged (see [this PR](https://github.com/camunda/infra-core/pull/9070) as reference).
Didn't happen though (see [this PR](https://github.com/camunda/infra-global-github-actions/pull/348)).
Adapted the config according to our [central one](https://github.com/camunda/infra-renovate-config/blob/main/default.json5#L232).
After merge I will retry the yet unmerged PR to validate.

ci(renovate): increase automerge rate for argocd

---

preview-env/create/README.md
preview-env/create/action.yml
preview-env/create/app-sync-status.sh
preview-env/create/templates/comment-failure.md
preview-env/create/templates/comment-success.md

Enrich the `preview-env/create` action with additional information that could help troubleshooting if anything goes wrong in a deployment.
Related: https://github.com/camunda/team-infrastructure/issues/521

feat(ci): add troubleshooting information to preview environment

---

preview-env/create/action.yml

Install `envsubst` binary for `preview-env/create` action. When the action is executed on a self-hosted runner then the deployment artifact create step would fail.
- Related
- https://github.com/camunda/team-infrastructure/issues/521
- https://camunda.slack.com/archives/C5AHF1D8T/p1740729769640149
- Tested on `web-modeler`
- https://github.com/camunda/web-modeler/actions/runs/13586248134/job/37981769877?pr=12687#step:7:1391

Install envsubst

---

.github/renovate.json5

Enable Renovate automerge for `gravitational/teleport-ent-distroless` patch releases.
Related: https://github.com/camunda/infra-global-github-actions/pull/362

chore(deps): enable renovate automerge for teleport-ent-distroless

---

fossa/analyze/action.yml
fossa/setup/action.yml

Related to https://github.com/camunda/team-infrastructure/issues/751.
Add new composite actions for FOSSA:
- `fossa/setup` to install the CLI
- `fossa/analyze` to run the analysis
The idea is to encapsulate interactions with the FOSSA CLI used in workflows across various product repositories. This approach simplifies maintenance (e.g., upgrading the CLI version) and abstracts unnecessary implementation details.

chore: add fossa-related composite actions

---

fossa/analyze/action.yml
fossa/info/action.yml
fossa/pr-check/action.yml

Related to https://github.com/camunda/team-infrastructure/issues/752.
Add new fossa-related composite actions to check PRs for newly introduced issues. It currently only handle license issues, but can be extended to security issues later.
The `fossa/pr-check` action relies on the `fossa test` command and includes a License Policy guard step, which fails if the PR introduces a new license issue and add an annotation to the job for visibility.

feat: add new fossa-related composite actions

---

actionlint/README.md
actionlint/action.yml

Add an optional input variable to the composite workflow that enables `actionlint` to use `shellcheck`.
Related: https://github.com/camunda/camunda/issues/31046

feat(actionlint): enable optional use of shellcheck

---

.github/workflows/retry-worfklow-run.yml

This PR is just a proposal.
I did not check whether there are any other fixes required within the workflow. This is just for reporting back the error and not actually rerunning (which seems to work).
Before it was just taking the workflowName, which can be the correct file name if a user doesn't overwrite the name. In that case it will default to the file name. The likelihood of users not overwriting the name is quite slim.
Therefore, we need to get the correct file name somehow differently as the run itself doesn't contain that, we're parsing it via the API.
Related to following failed job: https://github.com/camunda/infra-global-github-actions/actions/runs/15091530730/job/42420711579
```
notifying back to workflow=Tests - Integration - AWS OpenShift ROSA HCP Dual Region.yml ...
HTTP …
```

fix: retry-worfklow-run report back to workflow file

---

common-tooling/README.md
common-tooling/action.yml

Fixes: #432
Support the `build-essential` package installation.
It's disabled by default, so no change in the default behaviour of the GitHub Action.

feat(common-tooling): support build-essential

---

.github/workflows/retry-worfklow-run.yml
rerun-failed-run/README.md
rerun-failed-run/action.yml

Hey Infra 👋,
I have a small suggestion: Allow the retry action/workflow to retrigger the whole workflow, not just the failed jobs.
We have a use case where it would be beneficial for us to rerun the whole workflow instead of just the failed jobs. Since we already have the functionality available, I thought to simply extend it instead of recreating it on our side.
For existing users nothing changes as the default is to retry the failed jobs.
Related [gh run rerun docs](https://cli.github.com/manual/gh_run_rerun).
> Rerun an entire run, only failed jobs, or a specific job from a run.
Let me know if names should be changed or implemented differently.
We could also approach it from a different side to say `rerun-failed-jobs` or similar and make it the default to be true and have something …

chore: allow retry action and workflow to rerun whole workflow

---

submit-test-status/action.yml

Reading the test records from console had issues because of the escape characters, not its refactored and fixed

Fix reading record length from console
